### ISSUE TITLE
i18n for cookie-consent

### ISSUE THREAD

**Issue by bfredo123** [gethugothemes/hugo-modules#18]
It looks like the cookie-consent module cannot use i18n. It uses `cookies.content` and `cookies.button` without going through translations.
Is it possible to work this around? It would be quite useful (if not mandatory) for multilingual sites.
Many thanks!

**Comment by alex-feel** [comment]
This can be easily fixed as indicated here or even simpler (without moving the keys into `params.toml`): https://github.com/gethugothemes/hugo-modules/commit/3627f00b636edbde24c9fd3c2d5340fa9c6dbadd.

I can't make a pull request because I have a lot of other changes that are unlikely to be accepted.

**Comment by tfsomrat** [comment]
Hey @bfredo123, it's actually support multilingual. follow the steps

params.toml
```
[cookies]
enable = true
expire_days = 60
```

languages.toml
```
# for english
[en.params.cookies]
content = "This site uses cookies."
button = "I Accept"

# for french
[fr.params.cookies]
content = "Ce site utilise des cookies"
button = "J'accepte"
```

hope it will help. thanks
