### ISSUE TITLE
Duplicate content in search results

### ISSUE THREAD

**Issue by mbrn-in** [gethugothemes/hugo-modules#9]
Hi, thanks for the modules.

Looks like the search results shows some duplicate content. Please see the screenshot below for more details.

![image](https://github.com/gethugothemes/hugo-modules/assets/78746828/dd5e50db-9199-43b1-a0a4-f9928bf8d852)

Link: https://demo.gethugothemes.com/bookworm/site/?s=cl

**Comment by tfsojon** [comment]
Hello @mbrn-in 
Thank you for using our Hugo Module.
Basically the Bookworm Hugo themes post-content is duplicated from one post to another.
That's why the search result look like duplicated. but the search-result comes from the individual keyword match.

Try search with title, tag, category or something else to understand the scenario.
https://demo.gethugothemes.com/bookworm/site/?s=to

**Comment by mbrn-in** [comment]
Hi @tfsojon, thanks for your message.

The content on each page in Bookworm theme is different right?
The search index here https://demo.gethugothemes.com/bookworm/site/searchindex.json has unique content for each page. But the search shows duplicate results.

**Comment by tfsojon** [comment]
Ok don't worry. Will fix this by tomorrow

**Comment by tfsojon** [comment]
Hi @mbrn-in,
Update your Hugo module using `hugo mod clean && hugo mod get -u ./... && hugo mod tidy` 
or in our bookworm theme `npm run update-modules` / `yarn update-modules`

If module not updates correctly with the command
follow the steps
1 - delete `go.sum` file
2 - remove`github.com/gethugothemes/hugo-modules/search v0.0.0-******-*****` // indirect line
3 - then start hugo server
![image](https://github.com/gethugothemes/hugo-modules/assets/87603786/f9e81dfa-1f42-4b76-9eeb-e37a5a170bd2)

**Comment by mbrn-in** [comment]
Thanks for the fix @tfsojon . The problem has been solved.
